# Generated by Django 5.1.7 on 2025-03-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='date_issued',
            new_name='date_assigned',
        ),
        migrations.AddField(
            model_name='gun',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
